-- Create trending-images storage bucket for optimized thumbnails
-- This bucket will store compressed thumbnail versions of trending captures

-- Create the trending-images bucket (run this in Supabase dashboard or via API)
-- Note: Storage buckets are typically created via the Supabase dashboard or API, not SQL
-- But here's the equivalent SQL if your Supabase instance supports it

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'trending-images',
  'trending-images', 
  true,  -- Public bucket for fast access
  5242880,  -- 5MB file size limit
  ARRAY['image/jpeg', 'image/png', 'image/webp']  -- Allowed image types
)
ON CONFLICT (id) DO NOTHING;

-- Create RLS policies for the trending-images bucket
CREATE POLICY "Public Access" ON storage.objects
  FOR SELECT USING (bucket_id = 'trending-images');

CREATE POLICY "Authenticated users can upload" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'trending-images' 
    AND auth.role() = 'authenticated'
  );

CREATE POLICY "Users can update own images" ON storage.objects
  FOR UPDATE WITH CHECK (
    bucket_id = 'trending-images' 
    AND auth.uid()::text = (storage.foldername(name))[1]
  );

CREATE POLICY "Users can delete own images" ON storage.objects
  FOR DELETE USING (
    bucket_id = 'trending-images' 
    AND auth.uid()::text = (storage.foldername(name))[1]
  );

-- Create trending_images table to track thumbnail metadata
CREATE TABLE IF NOT EXISTS trending_images (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  capture_id UUID NOT NULL REFERENCES captures(id) ON DELETE CASCADE,
  habit_template_id UUID NOT NULL REFERENCES habit_templates(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  original_image_url TEXT NOT NULL,
  thumbnail_url TEXT NOT NULL,
  image_path TEXT NOT NULL,  -- Path in trending-images bucket
  width INTEGER,
  height INTEGER,
  file_size INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Ensure unique thumbnail per capture
  UNIQUE(capture_id)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_trending_images_habit_template ON trending_images(habit_template_id);
CREATE INDEX IF NOT EXISTS idx_trending_images_user ON trending_images(user_id);
CREATE INDEX IF NOT EXISTS idx_trending_images_created_at ON trending_images(created_at);

-- Enable RLS on trending_images table
ALTER TABLE trending_images ENABLE ROW LEVEL SECURITY;

-- RLS policies for trending_images table
CREATE POLICY "Public can read trending images" ON trending_images
  FOR SELECT USING (true);

CREATE POLICY "Authenticated users can insert trending images" ON trending_images
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Users can update own trending images" ON trending_images
  FOR UPDATE WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own trending images" ON trending_images
  FOR DELETE USING (auth.uid() = user_id);

-- Create function to automatically generate thumbnails when captures are made public
CREATE OR REPLACE FUNCTION create_trending_thumbnail()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  template_id UUID;
BEGIN
  -- Only process public captures with images
  IF NEW.is_public = true AND NEW.image_url IS NOT NULL THEN
    -- Get the habit template ID from user_habits
    SELECT uh.habit_template_id INTO template_id
    FROM user_habits uh
    WHERE uh.id = NEW.habit_id;
    
    -- Insert into trending_images table (thumbnail will be generated by app)
    INSERT INTO trending_images (
      capture_id,
      habit_template_id,
      user_id,
      original_image_url,
      thumbnail_url,
      image_path
    ) VALUES (
      NEW.id,
      template_id,
      NEW.user_id,
      NEW.image_url,
      NEW.image_url,  -- Will be updated with thumbnail URL by app
      'thumbnails/' || NEW.user_id::text || '/' || NEW.id::text || '.jpg'
    )
    ON CONFLICT (capture_id) DO UPDATE SET
      original_image_url = NEW.image_url,
      updated_at = NOW();
  END IF;
  
  RETURN NEW;
END;
$$;

-- Create trigger to automatically create trending thumbnails
DROP TRIGGER IF EXISTS trigger_create_trending_thumbnail ON captures;
CREATE TRIGGER trigger_create_trending_thumbnail
  AFTER INSERT OR UPDATE ON captures
  FOR EACH ROW
  EXECUTE FUNCTION create_trending_thumbnail();

-- Add comments
COMMENT ON TABLE trending_images IS 'Stores metadata for trending habit capture thumbnails';
COMMENT ON FUNCTION create_trending_thumbnail() IS 'Automatically creates trending thumbnail entries when captures are made public';
